/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as WeakPointsRouteImport } from './routes/weak-points'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const WeakPointsRoute = WeakPointsRouteImport.update({
  id: '/weak-points',
  path: '/weak-points',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/program': typeof ProgramRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/weak-points': typeof WeakPointsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/program': typeof ProgramRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/weak-points': typeof WeakPointsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/program': typeof ProgramRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/weak-points': typeof WeakPointsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/program' | '/progress' | '/settings' | '/skills' | '/weak-points'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/program' | '/progress' | '/settings' | '/skills' | '/weak-points'
  id:
    | '__root__'
    | '/'
    | '/program'
    | '/progress'
    | '/settings'
    | '/skills'
    | '/weak-points'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgramRoute: typeof ProgramRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  WeakPointsRoute: typeof WeakPointsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weak-points': {
      id: '/weak-points'
      path: '/weak-points'
      fullPath: '/weak-points'
      preLoaderRoute: typeof WeakPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgramRoute: ProgramRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  WeakPointsRoute: WeakPointsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
